dubbo:
    application:
        # ??? interface?instance?all???? all????????????????
        register-mode: all
        metadata-type: remote
        service-discovery:
            # ???
            # FORCE_INTERFACE????????????????????? 2.x ??
            # APPLICATION_FIRST????????/?????????
            # FORCE_APPLICATION????????????????????? 3.x ??
            migration: APPLICATION_FIRST
        name: dubbo-consumer
    registry:
        address: zookeeper://127.0.0.1:2181?init.timeout=60000
    #        address: zookeeper://121.5.7.221:2181?init.timeout=60000
    protocol:
        name: dubbo
        port: 20880
    # ????????????????????dev1
    consumer:
        group: dev
        timeout: 10000
    provider:
        group: dev
        timeout: 10000